# Site settings
title: Soreine
email: hello@soreine.dev
description: "Soreine's personal website" # > this means to ignore newlines until "baseurl:"
baseurl: "/old.soreine.github.io/" # the subpath of your site, e.g. /blog/
url: "http://soreine.dev" # the base hostname & protocol for your site
# disqus_short_name: soreine-github-io
enable_disqus: false
github_username: Soreine
permalink: pretty
exlude:
  - css/style.styl
  - Gemfile
  - Gemfile.lock
  - README.md
  - working/
# Stylus
# stylus:
#   compress: true
#   path: ./css/
#   include_css: true

# Build settings
markdown: kramdown
highlighter: rouge
